<?php

// $Id$

/**
 * @file
 * 
 * Place holder, for the moment objective forms doesn't rely on any hooks, or cached data.
 */

/**
 * Implements form_element_created hook.
 * 
 * @param FormElement $form_element 
 */
function objective_forms_form_element_created(FormElement $form_element) {
  module_load_include('inc', 'objective_forms', 'FormElementRegistry');
  $registry = FormElementRegistry::getInstance();
  $registry->registerCreated($form_element);
}

/**
 * Implements form_element_cloned hook.
 * 
 * @param hash $original_hash
 * @param FormElement $clone
 */
function objective_forms_form_element_cloned($original_hash, FormElement $clone) {
  module_load_include('inc', 'objective_forms', 'FormElementRegistry');
  $registry = FormElementRegistry::getInstance();
  $registry->registerClone($original_hash, $clone);
}

/**
 *
 * @param hash $hash
 */
function objective_forms_form_element_destroyed($hash) {
  module_load_include('inc', 'objective_forms', 'FormElementRegistry');
  $registry = FormElementRegistry::getInstance();
  $registry->registerDestroyed($hash); // Will never get called cause the Registry holds a reference to that element.
}

/**
 * Uses submitted post data to set the default values for the form.
 */
function objective_forms_set_default_values(array &$form, array &$form_state) {
  module_load_include('inc', 'objective_forms', 'FormPopulator');
  $populator = new FormPopulator(new FormValues($form_state, $form), $form_state);
  $populator->populate($form);
  return $form;
}

/**
 * !TEST CODE REMOVE! 
 */
function objective_forms_menu() {
  $items['objective'] = array(
    'title' => 'menu_item_title',
    'description' => 'menu_item_description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('objective_form'),
    'access arguments' => array('menu_item_access'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function objective_form(&$form_state) {
  module_load_include('inc', 'objective_forms', 'Form');
  module_load_include('inc', 'objective_forms', 'FormElement');
  $form = array(
    ''
  );
  $form = new Form($form_state, $form);
  $form->one = new FormElement();
  $form->one->two = new FormElement();
  $form['one']->type = 'textfield';
  $out = $form->toArray();
  return $out;
}

/**
 * !END TEST CODE!
 */