<?php

// $Id$

/**
 * @file
 * 
 * Place holder, for the moment objective forms doesn't rely on any hooks, or cached data.
 */

/**
 * Implements form_element_created hook.
 * 
 * @param FormElement $form_element 
 */
function objective_forms_form_element_created(FormElement $form_element) {
  module_load_include('inc', 'FormElementRegistry');
  $registry = FormElementRegistry::getInstance();
  $registry->registerCreated($form_element);
}

/**
 * Implements form_element_cloned hook.
 * 
 * @param hash $original_hash
 * @param FormElement $clone
 */
function objective_forms_form_element_cloned($original_hash, FormElement $clone) {
  module_load_include('inc', 'FormElementRegistry');
  $registy = FormElementRegistry::getInstance();
  $registry->registerClone($original_hash, $clone);
}

/**
 *
 * @param hash $hash
 */
function objective_forms_form_element_destroyed($hash) {
  module_load_include('inc', 'FormElementRegistry');
  $registy = FormElementRegistry::getInstance();
  $registry->registerDestroyed($hash); // Will never get called cause the Registry holds a reference to that element.
}